---
- name: setup everything
  hosts: hetzner
  remote_user: root

  ##
  # nginx
  ##
  tasks:
  - name: install nginx
    apt:
      name:
        - nginx
      state: present
      update_cache: yes
  ##
  # project dir
  ##
  - name: mkdir
    file:
      path: /home/www
      state: directory
      mode: '0755'
  ##
  # git
  ##
  - name: install git
    apt:
      name:
        - git
      state: present
  - git:
      repo: git@github.com:FirstLawofRobotics/instagram-imposter.git
      dest: /home/www
      force: yes
  ##
  # python and deps
  ##
  - name: install python3 dependencies
    apt:
      name:
        - software-properties-common
        - build-essential
        - python3-dev
      state: present
      update_cache: yes
  - apt_repository:
      repo: ppa:deadsnakes/ppa
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: install python3
    apt:
      name:
        - python3.8
        - python3-pip
        - python3-setuptools
  - name: install app requirements
    command:
      cmd:  pip3 install -r /home/www/requirements/production.txt 
  - name: install app requirements local
    command:
      cmd:  pip3 install -r /home/www/requirements/local.txt 
  - name: allowed hosts
    lineinfile:
      path: /home/www/config/settings/local.py
      regexp: 'ALLOWED_HOSTS'
      line: ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", "95.217.185.11"]
  - name: python setup tools
    command:
      cmd: python3 -m pip install --upgrade pip setuptools wheel
  ##
  # postgres
  ##
  - name: install postgres
    apt:
      name: 
        - postgresql
        - postgresql-contrib
        - python-psycopg2
        - libpq-dev
  ##
  # redis
  ##
  - name: install redis
    apt:
      name:
        - redis-server
  - name: redis settings
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'supervised'
      line: supervised systemd
  - name: restart redis
    service:
      name: redis
      state: restarted
  ##
  # celery
  ##
  - name: install celery
    pip:
      name: celery
  - name: kill previous celery
    shell: kill `ps -ef | grep celery | grep -v grep | awk '{print $2}'`
    ignore_errors: true
  - name: run celery worker
    shell: celery worker -A config.celery_app.app -l info &
    args:
      chdir: /home/www
