---
- name: install nginx
  hosts: hetzner
  remote_user: root

  tasks:
  - name: install nginx
    apt:
      name:
        - nginx
      state: present
      update_cache: yes
  - name: mkdir
    file:
      path: /home/www
      state: directory
      mode: '0755'
  - name: install git
    apt:
      name:
        - git
      state: present
  - git:
      repo: git@github.com:FirstLawofRobotics/instagram-imposter.git
      dest: /home/www
  - name: install python3 dependencies
    apt:
      name:
        - software-properties-common
        - build-essential
        - python3-dev
      state: present
      update_cache: yes
  - apt_repository:
      repo: ppa:deadsnakes/ppa
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: install python3
    apt:
      name:
        - python3.8
        - python3-pip
        - python3-setuptools
  - name: install postgres
    apt:
      name: 
        - postgresql
        - postgresql-contrib
        - python-psycopg2
        - libpq-dev
  - name: install app requirements
    command:
      cmd:  pip3 install -r /home/www/requirements/production.txt 
  - name: install app requirements local
    command:
      cmd:  pip3 install -r /home/www/requirements/local.txt 
  - name: collect static
    command:
      cmd: python3 /home/www/manage.py collectstatic
