---
- name: configure nvim and plugins
  hosts: localhost
  connection: local

  tasks:
  - name: install neovim plugin manager
    shell: |
      curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - name: pip3 neovim
    shell: |
      pip3 install --user neovim

  - name: create config dir
    shell: |
      mkdir -p ~/.config/nvim

  - name: copy nvim config
    copy:
      src: init.vim
      dest: ~/.config/nvim/init.vim

  - name: copy vim comments script
    copy:
      src: vcomments.vim
      dest: ~/.vcomments.vim

  - name: copy ack config
    copy:
      src: .ackrc
      dest: ~/.ackrc

  - name: copy tmux config
    copy:
      src: .tmux.conf
      dest: ~/.tmux.conf
  # tmux resurrect
  - name: tmux resurrect
    git: repo=https://github.com/tmux-plugins/tmux-resurrect dest=~/tmux/resurrect
  - name: tmux continuum
    git: repo=https://github.com/tmux-plugins/tmux-continuum dest=~/tmux/continuum
  # kitty themes configs
  - name: kitty themes
    git: repo=https://github.com/dexpota/kitty-themes.git dest=~/.config/kitty/kitty-themes
  - name: copy kitty theme github
    file:
      src: ~/.config/kitty/kitty-themes/themes/Github.conf
      dest: ~/.config/kitty/theme.conf
      state: link
  # kitty fonts
  - name: create font config dir
    shell: |
      mkdir -p ~/.config/fontconfig
  - name: copy firca code config
    copy:
      src: fonts.conf
      dest: ~/.config/fontconfig/fonts.conf
  # kitty config
  - name: copy kitty config
    copy:
      src: kitty.conf
      dest: ~/.config/kitty/kitty.conf
  # asdf
  - name: asdf install
    git: repo=https://github.com/asdf-vm/asdf.git dest=~/.asdf
  - name: asdf checkout
    shell: |
      cd ~/.asdf && git checkout "$(git describe --abbrev=0 --tags)"
  # ohmyzsh
  - name: oh-my-zsh install
    shell: |
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - name: copy ohmyzsh config
    copy:
      src: .zshrc
      dest: ~/.zshrc
  # asdf elixir and erlang
  - name: asdf erlang plugin
    shell: |
      asdf plugin-add erlang
  - name: asdf elixir plugin
    shell: |
      asdf plugin-add elixir
  - name: asdf install erlang
    shell: |
      asdf install erlang 23.0.2
  - name: asdf install elixir
    shell: |
      asdf install elixit 1.10.1
