---

- hosts: [hetzner-test, hetzner-prod]
  remote_user: root
  vars: 
    sys_packages: ["curl", "git", "ufw"]
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  roles:
   - role: security
