---

- include: roles/common/tasks/init_folders.yml
- include: roles/common/tasks/create_ssh_keys.yml

- name: Create init-letsencrypt from template
  template:
    src: templates/letsencrypt.sh
    dest: "{{ repo_folder }}init-letsencrypt.sh"
    mode: a+x
